In [3]:
!pip3 install numpy
import numpy as np

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 10.1 MB/s  0:00:00.0 MB/s eta 0:00:01


In [4]:
import numpy as np

arr_1d = np.arange(1, 11)
arr_2d = np.random.randint(1, 100, size=(3, 3))

print(arr_1d)
print(arr_2d)

[ 1  2  3  4  5  6  7  8  9 10]
[[21 25 66]
 [51 75 29]
 [67 72 18]]


In [6]:
print(np.sum(arr_2d))
print(np.mean(arr_2d))
print(np.max(arr_2d))

arr_2d = arr_2d * 2

arr_1d[arr_1d > 5] = 0
print(arr_1d)

424
47.111111111111114
75
[1 2 3 4 5 0 0 0 0 0]
